DROP TABLE IF EXISTS users, requests, items, comments, bookings;

DROP TYPE IF EXISTS booking_status;

CREATE TYPE booking_status as ENUM ('WAITING', 'APPROVED', 'REJECTED', 'CANCELED');

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(30) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS requests (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    description VARCHAR(512),
    requestor_id INTEGER REFERENCES users ON DELETE CASCADE,
    created_date TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS items (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(512),
    is_available BOOLEAN NOT NULL,
    owner_id INTEGER NOT NULL REFERENCES users ON DELETE CASCADE,
    request_id INTEGER REFERENCES requests ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS bookings (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    start_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    item_id INTEGER NOT NULL REFERENCES items ON DELETE CASCADE,
    booker_id INTEGER NOT NULL REFERENCES users ON DELETE CASCADE,
    status booking_status NOT NULL
);

CREATE TABLE IF NOT EXISTS comments (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    text VARCHAR(512),
    item_id INTEGER REFERENCES items ON DELETE CASCADE,
    author VARCHAR(255),
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL
);